/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rsubayaservertcp;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;

/**
 *
 * @author Vincent
 */
public class UIServerRSUBAYA extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form UIServerRSUBAYA
     */
    ArrayList<String> poliObgyn = new ArrayList<>();
    ArrayList<String> poliTumbuh = new ArrayList<>();
    ArrayList<String> poliPenyakitDalam = new ArrayList<>();
    ArrayList<String> panggilList = new ArrayList<>();

    public UIServerRSUBAYA() {
        initComponents();
        try {
            server = new ServerSocket(6100);
            if (thread == null) {
                thread = new Thread(this, "server");
                thread.start();
            }
        } catch (Exception e) {
        }
    }

    Socket client;
    ServerSocket server;
    public Thread thread;
    ArrayList<HandleSocketRSUBAYA> clientList = new ArrayList<>();
    int antriPoliO = 0;
    int antriPoliT = 0;
    int antriPoliP = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaServer = new javax.swing.JTextArea();
        btnPanggilO = new javax.swing.JButton();
        btnPanggilT = new javax.swing.JButton();
        btnPanggilP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("RS UBAYA");

        txtAreaServer.setColumns(20);
        txtAreaServer.setRows(5);
        jScrollPane1.setViewportView(txtAreaServer);

        btnPanggilO.setText("Panggil Obgyn");
        btnPanggilO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanggilOActionPerformed(evt);
            }
        });

        btnPanggilT.setText("Panggil Tumbuh");
        btnPanggilT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanggilTActionPerformed(evt);
            }
        });

        btnPanggilP.setText("Panggil Penyakit dalam");
        btnPanggilP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanggilPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPanggilO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPanggilT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPanggilP))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPanggilO)
                    .addComponent(btnPanggilT)
                    .addComponent(btnPanggilP))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanggilOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanggilOActionPerformed
        // TODO add your handling code here:
        if(poliObgyn.size() >= 1 & antriPoliO <poliObgyn.size()){
            broadCast("info-" + poliObgyn.get(antriPoliO) + "-anda telah dipanggil masuk");
            txtAreaServer.append("\n"+poliObgyn.get(antriPoliO) + " dipanggil");
            antriPoliO += 1;
            panggilList.add(antriPoliO + ": " + poliObgyn.get(antriPoliO-1) + " (Poli Obgyn)");
        }
    }//GEN-LAST:event_btnPanggilOActionPerformed

    private void btnPanggilTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanggilTActionPerformed
        // TODO add your handling code here:
        if(poliTumbuh.size() >= 1 & antriPoliT <poliTumbuh.size()){
            broadCast("info-" + poliTumbuh.get(antriPoliT) + "-anda telah dipanggil masuk");
            txtAreaServer.append("\n"+poliTumbuh.get(antriPoliT) + " dipanggil");
            antriPoliT += 1;
            panggilList.add(antriPoliT + ": " + poliTumbuh.get(antriPoliT-1) + " (Poli Tumbuh Kembang Anak)");
        }
        
    }//GEN-LAST:event_btnPanggilTActionPerformed

    private void btnPanggilPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanggilPActionPerformed
        // TODO add your handling code here:
        if(poliPenyakitDalam.size() >= 1 & antriPoliP <poliPenyakitDalam.size()){
            broadCast("info-" + poliPenyakitDalam.get(antriPoliP) + "-anda telah dipanggil masuk");
            txtAreaServer.append("\n"+poliPenyakitDalam.get(antriPoliP) + " dipanggil");
            antriPoliP += 1;
            panggilList.add(antriPoliP + ": " + poliPenyakitDalam.get(antriPoliP-1) + " (Poli Penyakit Dalam)");
        }
        
    }//GEN-LAST:event_btnPanggilPActionPerformed

    /**
     * @param args the command line arguments
     */
    @Override
    public void run() {
        try {
            while (true) {
                client = server.accept();
                HandleSocketRSUBAYA hs = new HandleSocketRSUBAYA(this, client);
                hs.start();
                clientList.add(hs);
            }
        } catch (Exception e) {
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIServerRSUBAYA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIServerRSUBAYA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIServerRSUBAYA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIServerRSUBAYA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIServerRSUBAYA().setVisible(true);
            }
        });
    }

    public void showPasien(String data, Socket client) {
        String[] dataPasien = data.split("-");
        String nama = dataPasien[0];
        String p = dataPasien[1];
        try {
            if ("batal".equals(dataPasien[1])) {
                txtAreaServer.append(nama + " Batal antri\n");
                System.out.println("batal");
                if ("1".equals(dataPasien[2])) {
                    poliObgyn.set(poliObgyn.indexOf(nama), " ");
                } else if ("2".equals(dataPasien[2])) {
                    poliTumbuh.set(poliTumbuh.indexOf(nama), " ");
                } else {
                    poliPenyakitDalam.set(poliPenyakitDalam.indexOf(nama), " ");
                }
            } else if ("display".equals(dataPasien[1])) {
                broadCast("info-broadcast-" + "Antrian sudah terpanggil:");
                String info = "";
                for(String pesan : panggilList)
                {
                    info += "info-broadcast-" + pesan + "\n";
                }
                System.out.println(info);
                broadCast(info);
                
            } else {
                int antri = 0;
                if (Integer.parseInt(p) <= 3) {
                    String poli = "";
                    boolean error = false;
                    if ("1".equals(p) & !poliObgyn.contains(nama)) {
                        poli = "Poli obgyn";
                        poliObgyn.add(nama);
                        antri = poliObgyn.indexOf(nama) + 1;
                    } else if ("2".equals(p) & !poliTumbuh.contains(nama)) {
                        poli = "Poli tumbuh kembang anak";
                        poliTumbuh.add(nama);
                        antri = poliTumbuh.indexOf(nama) + 1;
                    } else if ("3".equals(p) & !poliPenyakitDalam.contains(nama)) {
                        poli = "Poli penyakit dalam";
                        poliPenyakitDalam.add(nama);
                        antri = poliPenyakitDalam.indexOf(nama) + 1;
                    } else {
                        broadCast("info" + "-" + nama + "-" + "Nama sudah digunakan");
                        error = true;
                    }
                    if (!error) {
                        broadCast(nama + "-" + antri);
                        txtAreaServer.append(dataPasien[0] + ": " + poli + "\n");
                    }
                } else {
                    broadCast("info" + "-" + nama + "-" + "Poli hanya ada 3");
                }
            }
        } catch (Exception e) {
            System.out.println("Error show pasien");
        }
    }

    public void broadCast(String message) {
        for (HandleSocketRSUBAYA pasien : clientList) {
            pasien.kirimPesan(message + "\n");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPanggilO;
    private javax.swing.JButton btnPanggilP;
    private javax.swing.JButton btnPanggilT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaServer;
    // End of variables declaration//GEN-END:variables
}
